// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Request
{
  public struct ActiveSkill : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static ActiveSkill GetRootAsActiveSkill(ByteBuffer _bb) { return GetRootAsActiveSkill(_bb, new ActiveSkill()); }
    public static ActiveSkill GetRootAsActiveSkill(ByteBuffer _bb, ActiveSkill obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public ActiveSkill __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<ActiveSkill> CreateActiveSkill(FlatBufferBuilder builder,
        int id = 0) {
      builder.StartTable(1);
      ActiveSkill.AddId(builder, id);
      return ActiveSkill.EndActiveSkill(builder);
    }
  
    public static void StartActiveSkill(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
    public static Offset<ActiveSkill> EndActiveSkill(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<ActiveSkill>(o);
    }
  
    public struct Model
    {
      public int Id { get; set; }
    
      public Model(int id)
      {
        Id = id;
      }
    }
  
    public static byte[] Bytes(int id) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = ActiveSkill.CreateActiveSkill(builder, id);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(ActiveSkill).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(ActiveSkill).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Id);
    }
  };
}