// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Request
{
  public struct InactiveItem : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static InactiveItem GetRootAsInactiveItem(ByteBuffer _bb) { return GetRootAsInactiveItem(_bb, new InactiveItem()); }
    public static InactiveItem GetRootAsInactiveItem(ByteBuffer _bb, InactiveItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public InactiveItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  
    public static Offset<InactiveItem> CreateInactiveItem(FlatBufferBuilder builder,
        ulong id = 0) {
      builder.StartTable(1);
      InactiveItem.AddId(builder, id);
      return InactiveItem.EndInactiveItem(builder);
    }
  
    public static void StartInactiveItem(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
    public static Offset<InactiveItem> EndInactiveItem(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<InactiveItem>(o);
    }
  
    public struct Model
    {
      public ulong Id { get; set; }
    
      public Model(ulong id)
      {
        Id = id;
      }
    }
  
    public static byte[] Bytes(ulong id) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = InactiveItem.CreateInactiveItem(builder, id);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(InactiveItem).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(InactiveItem).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Id);
    }
  };
}