// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Request
{
  public struct UpdateNPC : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static UpdateNPC GetRootAsUpdateNPC(ByteBuffer _bb) { return GetRootAsUpdateNPC(_bb, new UpdateNPC()); }
    public static UpdateNPC GetRootAsUpdateNPC(ByteBuffer _bb, UpdateNPC obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public UpdateNPC __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public Vector2? Position { get { int o = __p.__offset(6); return o != 0 ? (Vector2?)(new Vector2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  
    public static Offset<UpdateNPC> CreateUpdateNPC(FlatBufferBuilder builder,
        int sequence = 0,
        Offset<Vector2> positionOffset = default(Offset<Vector2>)) {
      builder.StartTable(2);
      UpdateNPC.AddPosition(builder, positionOffset);
      UpdateNPC.AddSequence(builder, sequence);
      return UpdateNPC.EndUpdateNPC(builder);
    }
  
    public static void StartUpdateNPC(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Vector2> positionOffset) { builder.AddOffset(1, positionOffset.Value, 0); }
    public static Offset<UpdateNPC> EndUpdateNPC(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<UpdateNPC>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public FlatBuffers.Protocol.Request.Vector2.Model Position { get; set; }
    
      public Model(int sequence, FlatBuffers.Protocol.Request.Vector2.Model position)
      {
        Sequence = sequence;
        Position = position;
      }
    }
  
    public static byte[] Bytes(int sequence, FlatBuffers.Protocol.Request.Vector2.Model position) {
      var builder = new FlatBufferBuilder(512);
      var positionOffset = FlatBuffers.Protocol.Request.Vector2.CreateVector2(builder, position.X, position.Y);
      var offset = UpdateNPC.CreateUpdateNPC(builder, sequence, positionOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(UpdateNPC).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(UpdateNPC).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Position);
    }
  };
}