// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Request
{
  public struct Update : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Update GetRootAsUpdate(ByteBuffer _bb) { return GetRootAsUpdate(_bb, new Update()); }
    public static Update GetRootAsUpdate(ByteBuffer _bb, Update obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Update __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public Vector2? Position { get { int o = __p.__offset(4); return o != 0 ? (Vector2?)(new Vector2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
    public UpdateNPC? Mobs(int j) { int o = __p.__offset(6); return o != 0 ? (UpdateNPC?)(new UpdateNPC()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
    public int MobsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  
    public static Offset<Update> CreateUpdate(FlatBufferBuilder builder,
        Offset<Vector2> positionOffset = default(Offset<Vector2>),
        VectorOffset mobsOffset = default(VectorOffset)) {
      builder.StartTable(2);
      Update.AddMobs(builder, mobsOffset);
      Update.AddPosition(builder, positionOffset);
      return Update.EndUpdate(builder);
    }
  
    public static void StartUpdate(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Vector2> positionOffset) { builder.AddOffset(0, positionOffset.Value, 0); }
    public static void AddMobs(FlatBufferBuilder builder, VectorOffset mobsOffset) { builder.AddOffset(1, mobsOffset.Value, 0); }
    public static VectorOffset CreateMobsVector(FlatBufferBuilder builder, Offset<UpdateNPC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
    public static VectorOffset CreateMobsVectorBlock(FlatBufferBuilder builder, Offset<UpdateNPC>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
    public static void StartMobsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
    public static Offset<Update> EndUpdate(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Update>(o);
    }
  
    public struct Model
    {
      public FlatBuffers.Protocol.Request.Vector2.Model Position { get; set; }
      public List<FlatBuffers.Protocol.Request.UpdateNPC.Model> Mobs { get; set; }
    
      public Model(FlatBuffers.Protocol.Request.Vector2.Model position, List<FlatBuffers.Protocol.Request.UpdateNPC.Model> mobs)
      {
        Position = position;
        Mobs = mobs;
      }
    }
  
    public static byte[] Bytes(FlatBuffers.Protocol.Request.Vector2.Model position, List<FlatBuffers.Protocol.Request.UpdateNPC.Model> mobs) {
      var builder = new FlatBufferBuilder(512);
      var positionOffset = FlatBuffers.Protocol.Request.Vector2.CreateVector2(builder, position.X, position.Y);
      var mobsOffset = FlatBuffers.Protocol.Request.Update.CreateMobsVector(builder, mobs.Select(x => FlatBuffers.Protocol.Request.UpdateNPC.CreateUpdateNPC(builder, x.Sequence, FlatBuffers.Protocol.Request.Vector2.CreateVector2(builder, x.Position.X, x.Position.Y))).ToArray());
      var offset = Update.CreateUpdate(builder, positionOffset, mobsOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Update).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Update).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Position, model.Mobs);
    }
  };
}