// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol
{
  public struct CheatPosition : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static CheatPosition GetRootAsCheatPosition(ByteBuffer _bb) { return GetRootAsCheatPosition(_bb, new CheatPosition()); }
    public static CheatPosition GetRootAsCheatPosition(ByteBuffer _bb, CheatPosition obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public CheatPosition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public Position? Position { get { int o = __p.__offset(4); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
    public long Now { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  
    public static Offset<CheatPosition> CreateCheatPosition(FlatBufferBuilder builder,
        Offset<Position> positionOffset = default(Offset<Position>),
        long now = 0) {
      builder.StartTable(2);
      CheatPosition.AddNow(builder, now);
      CheatPosition.AddPosition(builder, positionOffset);
      return CheatPosition.EndCheatPosition(builder);
    }
  
    public static void StartCheatPosition(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(0, positionOffset.Value, 0); }
    public static void AddNow(FlatBufferBuilder builder, long now) { builder.AddLong(1, now, 0); }
    public static Offset<CheatPosition> EndCheatPosition(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<CheatPosition>(o);
    }
  
    public struct Model
    {
      public FlatBuffers.Protocol.Position.Model Position { get; set; }
      public long Now { get; set; }
    
      public Model(FlatBuffers.Protocol.Position.Model position, long now)
      {
        Position = position;
        Now = now;
      }
    }
  
    public static byte[] Bytes(FlatBuffers.Protocol.Position.Model position, long now) {
      var builder = new FlatBufferBuilder(512);
      var positionOffset = FlatBuffers.Protocol.Position.CreatePosition(builder, position.X, position.Y);
      var offset = CheatPosition.CreateCheatPosition(builder, positionOffset, now);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(nameof(CheatPosition).Length));
          writer.Write(Encoding.Default.GetBytes(nameof(CheatPosition)));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
  };
}