// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using System.Linq;

namespace FlatBuffers.Protocol
{
  public struct Hide : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Hide GetRootAsHide(ByteBuffer _bb) { return GetRootAsHide(_bb, new Hide()); }
    public static Hide GetRootAsHide(ByteBuffer _bb, Hide obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Hide __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<Hide> CreateHide(FlatBufferBuilder builder,
        int sequence = 0) {
      builder.StartTable(1);
      Hide.AddSequence(builder, sequence);
      return Hide.EndHide(builder);
    }
  
    public static void StartHide(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static Offset<Hide> EndHide(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Hide>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
    
      public Model(int sequence)
      {
        Sequence = sequence;
      }
    }
  
    public static byte[] Bytes(int sequence) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = Hide.CreateHide(builder, sequence);
      builder.Finish(offset.Value);
      return builder.DataBuffer.ToSizedArray();
    }
  };
}