// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol
{
  public struct PositionChanged : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static PositionChanged GetRootAsPositionChanged(ByteBuffer _bb) { return GetRootAsPositionChanged(_bb, new PositionChanged()); }
    public static PositionChanged GetRootAsPositionChanged(ByteBuffer _bb, PositionChanged obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public PositionChanged __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public Position? Position { get { int o = __p.__offset(6); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  
    public static Offset<PositionChanged> CreatePositionChanged(FlatBufferBuilder builder,
        int sequence = 0,
        Offset<Position> positionOffset = default(Offset<Position>)) {
      builder.StartTable(2);
      PositionChanged.AddPosition(builder, positionOffset);
      PositionChanged.AddSequence(builder, sequence);
      return PositionChanged.EndPositionChanged(builder);
    }
  
    public static void StartPositionChanged(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(1, positionOffset.Value, 0); }
    public static Offset<PositionChanged> EndPositionChanged(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<PositionChanged>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public FlatBuffers.Protocol.Position.Model Position { get; set; }
    
      public Model(int sequence, FlatBuffers.Protocol.Position.Model position)
      {
        Sequence = sequence;
        Position = position;
      }
    }
  
    public static byte[] Bytes(int sequence, FlatBuffers.Protocol.Position.Model position) {
      var builder = new FlatBufferBuilder(512);
      var positionOffset = FlatBuffers.Protocol.Position.CreatePosition(builder, position.X, position.Y);
      var offset = PositionChanged.CreatePositionChanged(builder, sequence, positionOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(nameof(PositionChanged).Length));
          writer.Write(Encoding.Default.GetBytes(nameof(PositionChanged)));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Position);
    }
  };
}