// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol
{
  public struct SelectListDialog : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static SelectListDialog GetRootAsSelectListDialog(ByteBuffer _bb) { return GetRootAsSelectListDialog(_bb, new SelectListDialog()); }
    public static SelectListDialog GetRootAsSelectListDialog(ByteBuffer _bb, SelectListDialog obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public SelectListDialog __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Index { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<SelectListDialog> CreateSelectListDialog(FlatBufferBuilder builder,
        int index = 0) {
      builder.StartTable(1);
      SelectListDialog.AddIndex(builder, index);
      return SelectListDialog.EndSelectListDialog(builder);
    }
  
    public static void StartSelectListDialog(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddIndex(FlatBufferBuilder builder, int index) { builder.AddInt(0, index, 0); }
    public static Offset<SelectListDialog> EndSelectListDialog(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<SelectListDialog>(o);
    }
  
    public struct Model
    {
      public int Index { get; set; }
    
      public Model(int index)
      {
        Index = index;
      }
    }
  
    public static byte[] Bytes(int index) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = SelectListDialog.CreateSelectListDialog(builder, index);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(nameof(SelectListDialog).Length));
          writer.Write(Encoding.Default.GetBytes(nameof(SelectListDialog)));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Index);
    }
  };
}