// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol
{
  public struct Show : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Show GetRootAsShow(ByteBuffer _bb) { return GetRootAsShow(_bb, new Show()); }
    public static Show GetRootAsShow(ByteBuffer _bb, Show obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Show __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  #if ENABLE_SPAN_T
    public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
  #else
    public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  #endif
    public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
    public Position? Position { get { int o = __p.__offset(8); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
    public bool Moving { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
    public int Direction { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<Show> CreateShow(FlatBufferBuilder builder,
        int sequence = 0,
        StringOffset nameOffset = default(StringOffset),
        Offset<Position> positionOffset = default(Offset<Position>),
        bool moving = false,
        int direction = 0) {
      builder.StartTable(5);
      Show.AddDirection(builder, direction);
      Show.AddPosition(builder, positionOffset);
      Show.AddName(builder, nameOffset);
      Show.AddSequence(builder, sequence);
      Show.AddMoving(builder, moving);
      return Show.EndShow(builder);
    }
  
    public static void StartShow(FlatBufferBuilder builder) { builder.StartTable(5); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(2, positionOffset.Value, 0); }
    public static void AddMoving(FlatBufferBuilder builder, bool moving) { builder.AddBool(3, moving, false); }
    public static void AddDirection(FlatBufferBuilder builder, int direction) { builder.AddInt(4, direction, 0); }
    public static Offset<Show> EndShow(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Show>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public string Name { get; set; }
      public FlatBuffers.Protocol.Position.Model Position { get; set; }
      public bool Moving { get; set; }
      public int Direction { get; set; }
    
      public Model(int sequence, string name, FlatBuffers.Protocol.Position.Model position, bool moving, int direction)
      {
        Sequence = sequence;
        Name = name;
        Position = position;
        Moving = moving;
        Direction = direction;
      }
    }
  
    public static byte[] Bytes(int sequence, string name, FlatBuffers.Protocol.Position.Model position, bool moving, int direction) {
      var builder = new FlatBufferBuilder(512);
      var nameOffset = builder.CreateString(name);
      var positionOffset = FlatBuffers.Protocol.Position.CreatePosition(builder, position.X, position.Y);
      var offset = Show.CreateShow(builder, sequence, nameOffset, positionOffset, moving, direction);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(nameof(Show).Length));
          writer.Write(Encoding.Default.GetBytes(nameof(Show)));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Name, model.Position, model.Moving, model.Direction);
    }
  };
}