// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct Action : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Action GetRootAsAction(ByteBuffer _bb) { return GetRootAsAction(_bb, new Action()); }
    public static Action GetRootAsAction(ByteBuffer _bb, Action obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Action __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public int Pattern { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<Action> CreateAction(FlatBufferBuilder builder,
        int sequence = 0,
        int pattern = 0) {
      builder.StartTable(2);
      Action.AddPattern(builder, pattern);
      Action.AddSequence(builder, sequence);
      return Action.EndAction(builder);
    }
  
    public static void StartAction(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddPattern(FlatBufferBuilder builder, int pattern) { builder.AddInt(1, pattern, 0); }
    public static Offset<Action> EndAction(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Action>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public int Pattern { get; set; }
    
      public Model(int sequence, int pattern)
      {
        Sequence = sequence;
        Pattern = pattern;
      }
    }
  
    public static byte[] Bytes(int sequence, int pattern) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = Action.CreateAction(builder, sequence, pattern);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Action).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Action).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Pattern);
    }
  };
}