// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct BuffStart : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static BuffStart GetRootAsBuffStart(ByteBuffer _bb) { return GetRootAsBuffStart(_bb, new BuffStart()); }
    public static BuffStart GetRootAsBuffStart(ByteBuffer _bb, BuffStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public BuffStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  #if ENABLE_SPAN_T
    public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
  #else
    public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  #endif
    public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  
    public static Offset<BuffStart> CreateBuffStart(FlatBufferBuilder builder,
        StringOffset idOffset = default(StringOffset)) {
      builder.StartTable(1);
      BuffStart.AddId(builder, idOffset);
      return BuffStart.EndBuffStart(builder);
    }
  
    public static void StartBuffStart(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
    public static Offset<BuffStart> EndBuffStart(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<BuffStart>(o);
    }
  
    public struct Model
    {
      public string Id { get; set; }
    
      public Model(string id)
      {
        Id = id;
      }
    }
  
    public static byte[] Bytes(string id) {
      var builder = new FlatBufferBuilder(512);
      var idOffset = builder.CreateString(id);
      var offset = BuffStart.CreateBuffStart(builder, idOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(BuffStart).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(BuffStart).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Id);
    }
  };
}