// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct Damaged : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Damaged GetRootAsDamaged(ByteBuffer _bb) { return GetRootAsDamaged(_bb, new Damaged()); }
    public static Damaged GetRootAsDamaged(ByteBuffer _bb, Damaged obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Damaged __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public int Damage { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<Damaged> CreateDamaged(FlatBufferBuilder builder,
        int sequence = 0,
        int damage = 0) {
      builder.StartTable(2);
      Damaged.AddDamage(builder, damage);
      Damaged.AddSequence(builder, sequence);
      return Damaged.EndDamaged(builder);
    }
  
    public static void StartDamaged(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(1, damage, 0); }
    public static Offset<Damaged> EndDamaged(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Damaged>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public int Damage { get; set; }
    
      public Model(int sequence, int damage)
      {
        Sequence = sequence;
        Damage = damage;
      }
    }
  
    public static byte[] Bytes(int sequence, int damage) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = Damaged.CreateDamaged(builder, sequence, damage);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Damaged).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Damaged).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Damage);
    }
  };
}