// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct ExpChange : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static ExpChange GetRootAsExpChange(ByteBuffer _bb) { return GetRootAsExpChange(_bb, new ExpChange()); }
    public static ExpChange GetRootAsExpChange(ByteBuffer _bb, ExpChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public ExpChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public long Exp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  
    public static Offset<ExpChange> CreateExpChange(FlatBufferBuilder builder,
        long exp = 0) {
      builder.StartTable(1);
      ExpChange.AddExp(builder, exp);
      return ExpChange.EndExpChange(builder);
    }
  
    public static void StartExpChange(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddExp(FlatBufferBuilder builder, long exp) { builder.AddLong(0, exp, 0); }
    public static Offset<ExpChange> EndExpChange(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<ExpChange>(o);
    }
  
    public struct Model
    {
      public long Exp { get; set; }
    
      public Model(long exp)
      {
        Exp = exp;
      }
    }
  
    public static byte[] Bytes(long exp) {
      var builder = new FlatBufferBuilder(512);
    
      var offset = ExpChange.CreateExpChange(builder, exp);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(ExpChange).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(ExpChange).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Exp);
    }
  };
}