// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct Object : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Object GetRootAsObject(ByteBuffer _bb) { return GetRootAsObject(_bb, new Object()); }
    public static Object GetRootAsObject(ByteBuffer _bb, Object obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Object __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public int Sequence { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  #if ENABLE_SPAN_T
    public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
  #else
    public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  #endif
    public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
    public int Type { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
    public Position? Position { get { int o = __p.__offset(10); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
    public bool Moving { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
    public int Direction { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<Object> CreateObject(FlatBufferBuilder builder,
        int sequence = 0,
        StringOffset nameOffset = default(StringOffset),
        int type = 0,
        Offset<Position> positionOffset = default(Offset<Position>),
        bool moving = false,
        int direction = 0) {
      builder.StartTable(6);
      Object.AddDirection(builder, direction);
      Object.AddPosition(builder, positionOffset);
      Object.AddType(builder, type);
      Object.AddName(builder, nameOffset);
      Object.AddSequence(builder, sequence);
      Object.AddMoving(builder, moving);
      return Object.EndObject(builder);
    }
  
    public static void StartObject(FlatBufferBuilder builder) { builder.StartTable(6); }
    public static void AddSequence(FlatBufferBuilder builder, int sequence) { builder.AddInt(0, sequence, 0); }
    public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
    public static void AddType(FlatBufferBuilder builder, int type) { builder.AddInt(2, type, 0); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(3, positionOffset.Value, 0); }
    public static void AddMoving(FlatBufferBuilder builder, bool moving) { builder.AddBool(4, moving, false); }
    public static void AddDirection(FlatBufferBuilder builder, int direction) { builder.AddInt(5, direction, 0); }
    public static Offset<Object> EndObject(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Object>(o);
    }
  
    public struct Model
    {
      public int Sequence { get; set; }
      public string Name { get; set; }
      public int Type { get; set; }
      public FlatBuffers.Protocol.Response.Position.Model Position { get; set; }
      public bool Moving { get; set; }
      public int Direction { get; set; }
    
      public Model(int sequence, string name, int type, FlatBuffers.Protocol.Response.Position.Model position, bool moving, int direction)
      {
        Sequence = sequence;
        Name = name;
        Type = type;
        Position = position;
        Moving = moving;
        Direction = direction;
      }
    }
  
    public static byte[] Bytes(int sequence, string name, int type, FlatBuffers.Protocol.Response.Position.Model position, bool moving, int direction) {
      var builder = new FlatBufferBuilder(512);
      var nameOffset = builder.CreateString(name);
      var positionOffset = FlatBuffers.Protocol.Response.Position.CreatePosition(builder, position.X, position.Y);
      var offset = Object.CreateObject(builder, sequence, nameOffset, type, positionOffset, moving, direction);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Object).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Object).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Sequence, model.Name, model.Type, model.Position, model.Moving, model.Direction);
    }
  };
}