// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct Portal : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Portal GetRootAsPortal(ByteBuffer _bb) { return GetRootAsPortal(_bb, new Portal()); }
    public static Portal GetRootAsPortal(ByteBuffer _bb, Portal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Portal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public Position? Position { get { int o = __p.__offset(4); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
    public string Map { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  #if ENABLE_SPAN_T
    public Span<byte> GetMapBytes() { return __p.__vector_as_span<byte>(6, 1); }
  #else
    public ArraySegment<byte>? GetMapBytes() { return __p.__vector_as_arraysegment(6); }
  #endif
    public byte[] GetMapArray() { return __p.__vector_as_array<byte>(6); }
  
    public static Offset<Portal> CreatePortal(FlatBufferBuilder builder,
        Offset<Position> positionOffset = default(Offset<Position>),
        StringOffset mapOffset = default(StringOffset)) {
      builder.StartTable(2);
      Portal.AddMap(builder, mapOffset);
      Portal.AddPosition(builder, positionOffset);
      return Portal.EndPortal(builder);
    }
  
    public static void StartPortal(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(0, positionOffset.Value, 0); }
    public static void AddMap(FlatBufferBuilder builder, StringOffset mapOffset) { builder.AddOffset(1, mapOffset.Value, 0); }
    public static Offset<Portal> EndPortal(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Portal>(o);
    }
  
    public struct Model
    {
      public FlatBuffers.Protocol.Response.Position.Model Position { get; set; }
      public string Map { get; set; }
    
      public Model(FlatBuffers.Protocol.Response.Position.Model position, string map)
      {
        Position = position;
        Map = map;
      }
    }
  
    public static byte[] Bytes(FlatBuffers.Protocol.Response.Position.Model position, string map) {
      var builder = new FlatBufferBuilder(512);
      var positionOffset = FlatBuffers.Protocol.Response.Position.CreatePosition(builder, position.X, position.Y);
      var mapOffset = builder.CreateString(map);
      var offset = Portal.CreatePortal(builder, positionOffset, mapOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Portal).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Portal).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Position, model.Map);
    }
  };
}