// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct Show : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static Show GetRootAsShow(ByteBuffer _bb) { return GetRootAsShow(_bb, new Show()); }
    public static Show GetRootAsShow(ByteBuffer _bb, Show obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Show __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public Object? Objects(int j) { int o = __p.__offset(4); return o != 0 ? (Object?)(new Object()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
    public int ObjectsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
    public Character? Characters(int j) { int o = __p.__offset(6); return o != 0 ? (Character?)(new Character()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
    public int CharactersLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  
    public static Offset<Show> CreateShow(FlatBufferBuilder builder,
        VectorOffset objectsOffset = default(VectorOffset),
        VectorOffset charactersOffset = default(VectorOffset)) {
      builder.StartTable(2);
      Show.AddCharacters(builder, charactersOffset);
      Show.AddObjects(builder, objectsOffset);
      return Show.EndShow(builder);
    }
  
    public static void StartShow(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddObjects(FlatBufferBuilder builder, VectorOffset objectsOffset) { builder.AddOffset(0, objectsOffset.Value, 0); }
    public static VectorOffset CreateObjectsVector(FlatBufferBuilder builder, Offset<Object>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
    public static VectorOffset CreateObjectsVectorBlock(FlatBufferBuilder builder, Offset<Object>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
    public static void StartObjectsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
    public static void AddCharacters(FlatBufferBuilder builder, VectorOffset charactersOffset) { builder.AddOffset(1, charactersOffset.Value, 0); }
    public static VectorOffset CreateCharactersVector(FlatBufferBuilder builder, Offset<Character>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
    public static VectorOffset CreateCharactersVectorBlock(FlatBufferBuilder builder, Offset<Character>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
    public static void StartCharactersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
    public static Offset<Show> EndShow(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<Show>(o);
    }
  
    public struct Model
    {
      public List<FlatBuffers.Protocol.Response.Object.Model> Objects { get; set; }
      public List<FlatBuffers.Protocol.Response.Character.Model> Characters { get; set; }
    
      public Model(List<FlatBuffers.Protocol.Response.Object.Model> objects, List<FlatBuffers.Protocol.Response.Character.Model> characters)
      {
        Objects = objects;
        Characters = characters;
      }
    }
  
    public static byte[] Bytes(List<FlatBuffers.Protocol.Response.Object.Model> objects, List<FlatBuffers.Protocol.Response.Character.Model> characters) {
      var builder = new FlatBufferBuilder(512);
      var objectsOffset = FlatBuffers.Protocol.Response.Show.CreateObjectsVector(builder, objects.Select(x => FlatBuffers.Protocol.Response.Object.CreateObject(builder, x.Sequence, builder.CreateString(x.Name), x.Type, FlatBuffers.Protocol.Response.Vector2.CreateVector2(builder, x.Position.X, x.Position.Y), x.Moving, x.Direction)).ToArray());
      var charactersOffset = FlatBuffers.Protocol.Response.Show.CreateCharactersVector(builder, characters.Select(x => FlatBuffers.Protocol.Response.Character.CreateCharacter(builder, x.Sequence, builder.CreateString(x.Name), FlatBuffers.Protocol.Response.Vector2.CreateVector2(builder, x.Position.X, x.Position.Y), x.Moving, x.Direction, FlatBuffers.Protocol.Response.Character.CreateEquipmentVector(builder, x.Equipment.Select(x1 => FlatBuffers.Protocol.Response.Equipment.CreateEquipment(builder, x1.Id, builder.CreateString(x1.Name), x1.Type)).ToArray()))).ToArray());
      var offset = Show.CreateShow(builder, objectsOffset, charactersOffset);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(Show).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(Show).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Objects, model.Characters);
    }
  };
}