// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;
using global::System.Linq;
using global::System.IO;
using global::System.Text;

namespace FlatBuffers.Protocol.Response
{
  public struct SkillLevelUp : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
    public static SkillLevelUp GetRootAsSkillLevelUp(ByteBuffer _bb) { return GetRootAsSkillLevelUp(_bb, new SkillLevelUp()); }
    public static SkillLevelUp GetRootAsSkillLevelUp(ByteBuffer _bb, SkillLevelUp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public SkillLevelUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }
  
    public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  #if ENABLE_SPAN_T
    public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
  #else
    public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
  #endif
    public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
    public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  
    public static Offset<SkillLevelUp> CreateSkillLevelUp(FlatBufferBuilder builder,
        StringOffset idOffset = default(StringOffset),
        int level = 0) {
      builder.StartTable(2);
      SkillLevelUp.AddLevel(builder, level);
      SkillLevelUp.AddId(builder, idOffset);
      return SkillLevelUp.EndSkillLevelUp(builder);
    }
  
    public static void StartSkillLevelUp(FlatBufferBuilder builder) { builder.StartTable(2); }
    public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
    public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
    public static Offset<SkillLevelUp> EndSkillLevelUp(FlatBufferBuilder builder) {
      int o = builder.EndTable();
      return new Offset<SkillLevelUp>(o);
    }
  
    public struct Model
    {
      public string Id { get; set; }
      public int Level { get; set; }
    
      public Model(string id, int level)
      {
        Id = id;
        Level = level;
      }
    }
  
    public static byte[] Bytes(string id, int level) {
      var builder = new FlatBufferBuilder(512);
      var idOffset = builder.CreateString(id);
      var offset = SkillLevelUp.CreateSkillLevelUp(builder, idOffset, level);
      builder.Finish(offset.Value);
      
      var bytes = builder.DataBuffer.ToSizedArray();
      using (var mstream = new MemoryStream())
      {
        using (var writer = new BinaryWriter(mstream))
        {
          writer.Write(BitConverter.ToInt32(BitConverter.GetBytes(bytes.Length).Reverse().ToArray(), 0));
          writer.Write((byte)(typeof(SkillLevelUp).FullName.Length));
          writer.Write(Encoding.Default.GetBytes(typeof(SkillLevelUp).FullName));
          writer.Write(bytes);
          writer.Flush();
          return mstream.ToArray();
        }
      }
    }
    
    public static byte[] Bytes(Model model) {
      return Bytes(model.Id, model.Level);
    }
  };
}